---
- name: rename hetzner volumes in /mnt/
  hosts: backup
  become: true
  tasks:
    - name: Copy mount volume rename script
      copy:
        src: scripts/rename_volumes.sh
        dest: /tmp/rename_volumes.sh
        mode: +x

    - name: Execute the script
      shell: /tmp/rename_volumes.sh

    - name: Reboot server
      ansible.builtin.reboot:
        reboot_timeout: 25

# chown minio:minio /mnt/disk1 /mnt/disk2 /mnt/disk3 /mnt/disk4

