---
- name: Configure MinIO Custom DNS mappings
  hosts: backup, nginx-minio-lb
  become: yes
  vars:
    dns_mappings:
      - hostname: "minio-1.ujstor.com"
        ip_address: "91.107.208.20"
      - hostname: "minio-2.ujstor.com"
        ip_address: "5.75.139.83"
      - hostname: "minio-3.ujstor.com"
        ip_address: "65.109.9.72"
      - hostname: "minio.ujstor.com"
        ip_address: "49.13.73.3"

  tasks:
    - name: Configure DNS mappings
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip_address }} {{ item.hostname }}"
        state: present
      loop: "{{ dns_mappings }}"
