---
- name: Update package lists
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade all packages
  ansible.builtin.apt: 
    upgrade: true

- name: Install public AuthorizedKeysFile
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/hetzner_key.pub') }}"

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - ufw
    - fail2ban

- name: Allow incoming traffic on specified ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22

- name: Configure Fail2Ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: SSH Hardening for root user
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      PermitRootLogin yes
      PasswordAuthentication no
      X11Forwarding no
      MaxAuthTries 2
      AllowTcpForwarding no
      AllowAgentForwarding no
      AuthorizedKeysFile .ssh/authorized_keys

- name: restart sshd
  service:
    name: sshd
    state: restarted