---
- hosts: traefik-lb
  become: yes
  become_user: root
  tasks:
    - name: Allow incoming traffic on specified ports
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 443