---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install public AuthorizedKeysFile
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/hetzner_key.pub') }}"

