---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
        - fail2ban

    - name: Allow incoming traffic on specified ports
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443

    - name: Configure Fail2Ban
      template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify: restart fail2ban

    - name: SSH Hardening for root user
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          PermitRootLogin yes
          PasswordAuthentication no
          X11Forwarding no
          MaxAuthTries 2
          AllowTcpForwarding no
          AllowAgentForwarding no
          AuthorizedKeysFile .ssh/authorized_keys
      notify: restart sshd

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

    - name: restart sshd
      service:
        name: sshd
        state: restarted