---
- import_playbook: unique_templates_config/playbook_dns_backup_lb.yml

- name: Install minIO
  hosts: backup
  become: true
  ignore_unreachable: true
  gather_facts: true
  vars:
    minio_server_cluster_nodes:
      ["https://minio{1...3}.ujstor.com:{{ minio_server_port }}/mnt/disk{1...4}/minio"]

    minio_server_port: "9091"
    minio_console_port: "9092"

    minio_root_user: "ujstor"
    minio_root_password: "roottoor123"

    minio_validate_certificate: true
    minio_alias: "myminio"

    minio_url: "https://minio.ujstor.com:{{ minio_server_port }}"

  roles:
    - role: common
    - role: minio

  tasks:
    - name: Allow http, UI and S3 API ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 9091
        - 9092
        - 443
        - 80
      notify: restart minio

  handlers:
    - name: restart minio
      ansible.builtin.systemd_service:
        name: minio.service
        state: restarted