---
- import_playbook: unique_templates_config/playbook_dns_backup_lb.yml

- name: Configure Nginx as Load Balancer for MinIO cluster
  hosts: nginx-minio-lb
  become: true
  roles:
    - role: common

  vars:
    minio_servers:
      - 91.107.208.20
      - 65.109.9.72
      - 5.75.139.83
    minio_port: 9091
    console_port: 9092
    console_domain: minio-console.ujstor.com
    minio_domain: minio.ujstor.com

  tasks:
    - name: Install Nginx
      include_role:
        name: nginx

    - name: Create NGINX configuration directory
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Create nginx group
      group:
        name: nginx
        state: present

    - name: Create nginx system user
      user:
        name: nginx
        system: yes
        createhome: no
        shell: /bin/false
        group: nginx
        state: present

    - name: Nginx configuration file
      template:
        src: unique_templates_config/minio_lb/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx

    - name: Allow http, UI and S3 API ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 80
        - 9091
        - 9092

  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd_service:
        name: nginx.service
        state: reloaded

# sudo adduser --system --no-create-home --disabled-login --group nginx
