---
- import_playbook: ../roles/coolify/task/ufw_master.yml
- import_playbook: ../roles/coolify/task/ufw_node.yml

- hosts: coolify-master
  become: yes
  become_user: root
  tasks:
    - name: Download Coolify installation script
      get_url:
        url: "https://cdn.coollabs.io/coolify/install.sh"
        dest: "/tmp/install.sh"
        mode: "0644"

    - name: Execute Coolify installation script
      command: "bash /tmp/install.sh"
