---
- import_playbook: unique_templates_config/playbook_dns_backup_lb.yml

- name: Install minIO
  hosts: backup
  become: true
  ignore_unreachable: true

  roles:
    - role: common
    - role: minio

  vars:
    minio_server_cluster_nodes:
      ["http://minio-{1...3}.ujstor.com:9000/mnt/disk{1...4}/minio"]
    minio_server_env_extra: 'MINIO_ROOT_USER: "ujstor" MINIO_ROOT_PASSWORD: "roottoor!" MINIO_SERVER_URL: "minio.ujstor.com:9000"'

  tasks:
    - name: Allow http, UI and S3 API ports
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 9000
        - 9001
      notify: Restart Nginx

  #   - name: Check if cert directory exists
  #     stat:
  #       path: ${HOME}/.minio/certs
  #     register: dir_check

  #   - name: Create cert directory
  #     file:
  #       path: ${HOME}/.minio/certs
  #       state: directory
  #     when: not dir_check.stat.exists

  #   - name: Copy openssl crt
  #     copy:
  #       src: unique_templates_config/scripts/local-openssl/ujstor.com.crt
  #       dest: ${HOME}/.minio/certs

  #   - name: Copy openssl csr
  #     copy:
  #       src: unique_templates_config/scripts/local-openssl/ujstor.com.csr
  #       dest: ${HOME}/.minio/certs

  #   - name: Copy mount volume rename script
  #     copy:
  #       src: unique_templates_config/scripts/rename_volumes.sh
  #       dest: /tmp/rename_volumes.sh
  #       mode: +x

  #   - name: Execute the script
  #     shell: /tmp/rename_volumes.sh

  #   - name: Reboot server
  #     shell: reboot
  #     async: 1
  #     poll: 0
  
  handlers:
    - name: Reload NGINX
      ansible.builtin.systemd_service:
        name: minio.service
        state: reloaded