---
- import_playbook: unique_templates_config/playbook_dns_backup_lb.yml

- name: Configure NGINX Load Balancer
  hosts: nginx-lb
  become: true

  vars:
    backend_servers:
      - 10.0.1.1
      - 10.0.1.2
      - 10.0.1.3
      - 10.0.1.4
    domains:
      - name: domain1.net
        port: 4000
      - name: domain2.net
        port: 5000
      - name: xyz.domain
        port: 8080

  tasks:
    - name: Install NGINX
      include_role:
        name: nginx
      
    - name: Create NGINX configuration directory
      file:
        path: /etc/nginx/conf.d
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Create Nginx configuration file
      template:
        src: unique_templates_config/coolify_lb/nginx_coolify.conf.j2
        dest: /etc/nginx/nginx.conf

  handlers:
    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded
