### Site metadata ###

site_name: Deployment Cluster Docs
site_description: Official documentation for Deployment Cluste 
site_url: https://ujstor.github.io/deployment-cluster-s3-db/

repo_url: https://github.com/Ujstor/deployment-cluster-s3-db

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.expand
    - toc.flow
    - navigation.top
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home: index.md
  - Create infrastructure: create_infrastructure.md
  - Playbooks:
    - MinIO: playbooks/minio_playbook.md
    - Coolify: playbooks/coolify_playbook.md
  - Roles:
    - MinIO: roles/minio.md
    - Nginx: roles/nginx.md
    - Psql: roles/psql.md
  - Terminal output:
     - Terraform: terminal/terraform.md
     - Coolify: terminal/coolify_ansible.md
     - MinIO: terminal/minio_ansible.md
     - Psql: terminal/db_ansible.md

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ujstor
        name: GitHub
    generator: false
copyright: Copyright &copy; 2024 Ujstor